### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ian-whitestone** [get-select/dbt-snowflake-monitoring#10]
- [ ] Full bill daily & hourly breakdowns
- [ ] Table access history
- [ ] Unused tables & associated costs
- [ ] Cluster health snapshotting

**Comment by NiallRees** [comment]
Hourly not achievable for storage as it's calculated at the daily level, unless we just divided up the storage evenly across each other. At the hourly grain, it makes sense to me to create separate tables for each usage type so that we can add lots of usage type specific columns.

**Comment by ian-whitestone** [comment]
Separate issues created for each.
